updateDocsComment: >
  Thanks for opening this pull request! The maintainers of this repository would appreciate it if you would update some of our documentation based on your changes.

updateDocsWhiteList:
  - bug
  - chore

updateDocsTargetFiles:
  - README.md
  - docs/

