name: Bundler

on: create

jobs:
  autocommit:
    name: Update to stable dependencies
    if: startsWith(github.ref, 'refs/heads/release/')
    runs-on: ubuntu-latest
    container:
      image: atk4/image:latest # https://github.com/atk4/image
    steps:
      - uses: actions/checkout@master
      - name: Update CDN destination
        run: |
          v=$(echo ${{ github.ref }} | cut -d / -f 4)
          echo "::set-env name=version::$v"

          git branch
          sed -i "s|'https://raw.githubusercontent.com/atk4/ui/.*/public',|'https://cdn.jsdelivr.net/gh/atk4/ui@$v/public',|" src/App.php
          sed -i "s|public \$version.*|public \$version = '$v';|" src/App.php

      - uses: teaminkling/autocommit@master
        with:
          commit-message: Update versions for develop
      - uses: ad-m/github-push-action@master
        with:
          branch: feature/${{ env.version }}-cdn-update
          force: true # in case of repeat run
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: pull-request
        uses: romaninsh/pull-request@master
        with:
          source_branch: feature/${{ env.version }}-cdn-update
          destination_branch: develop
          pr_title: "Updating CDN link to use @${{ env.version }}"
          pr_body: |
            Compiled JS files from last release are here:

              https://cdn.jsdelivr.net/gh/atk4/ui@${{ env.version }}/public/

          pr_reviewer: "romaninsh"
          pr_assignee: "romaninsh"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update to stable dependencies
        run: |
          # replaces X keys with X-release keys
          jq '. as $in | reduce (keys_unsorted[] | select(endswith("-release")|not)) as $k ({}; . + {($k) : (($k + "-release") as $kr | $in | if has($kr) then .[$kr] else .[$k] end) } )' < composer.json > tmp && mv tmp composer.json

      - name: Compile JS files for CDN
        run: |
          npm install -g less-plugin-clean-css
          (cd js; npm install; npm run build; cd ..)
          lessc public/agileui.less public/agileui.css  --clean-css="--s1 --advanced --compatibility=ie8" --source-map
          uglifyjs --compress -- public/agileui.js > public/agileui.min.js
          echo '!agileui.css' >> public/.gitignore
          echo '!agileui.css.map' >> public/.gitignore
          echo '!agileui.min.js' >> public/.gitignore
          echo '!atkjs-ui.js' >> public/.gitignore
          echo '!atkjs-ui.min.js' >> public/.gitignore
          git add public

      - uses: teaminkling/autocommit@master
        with:
          commit-message: Setting current dependencies and complied JS
      - uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

#      - name: pull-request-action
#        uses: vsoch/pull-request-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          PULL_REQUEST_BRANCH: "master"
#          PULL_REQUEST_TITLE: "Releasing ${{ github.ref }} into master"
#          PULL_REQUEST_BODY: |
#            - [ ] Review changes (must include stable dependencies)
#            - [ ] Merge this PR into master (will delete ${{ github.ref }})
#            - [ ] Go to Releases and create TAG from master
#
#            Do not merge master into develop
#

      - name: pull-request
        uses: romaninsh/pull-request@master
        with:
          source_branch: "release/${{ env.version }}"
          destination_branch: "master"          # If blank, default: master
          pr_title: "Releasing ${{ github.ref }} into master"
          pr_body: |
            - [ ] Review changes (must include stable dependencies)
            - [ ] Merge this PR into master (will delete ${{ github.ref }})
            - [ ] Go to Releases and create TAG from master
            Do not merge master into develop
          pr_reviewer: "romaninsh"
          pr_assignee: "romaninsh"
          github_token: ${{ secrets.GITHUB_TOKEN }}
#
