name: Bundler

on: create

jobs:
  autocommit:
    name: Update to stable dependencies
    if: startsWith(github.ref, 'refs/heads/release/')
    runs-on: ubuntu-latest
    container:
      image: atk4/image:latest # https://github.com/atk4/image
    steps:
      - uses: actions/checkout@master
      - name: Update CDN destination
        shell: bash
        run: |
          $SHELL --version
          v=$(echo ${{ github.ref }} | cut -d / -f 4)
          echo "::set-env name=version::$v"

          git branch
          #sed -i "s|'https://cdn.jsdelivr.net/gh/atk4/ui@develop/public.*|'https://cdn.jsdelivr.net/gh/atk4/ui@$v/public',|" src/App.php
          # it was develop, it can stay develop for DEVELOP branch, so we see changes to JS right away.

          # Set next version for develop branch 2.3 -> 2.4.0-BETA
          a=( ${v//./ } )
          nv=${a[0]}"."$(( ${a[1]} +1 ))".0-BETA"
          sed -i "s|public \$version.*|public \$version = '$nv';|" src/App.php
          git config --global user.email "bundler@agiletoolkit.org"
          git config --global user.name "Release Bundler"
          git commit -am "Update versions for develop"

      - uses: ad-m/github-push-action@master
        with:
          branch: feature/${{ env.version }}-cdn-update
          force: true # in case of repeat run
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: pull-request
        uses: romaninsh/pull-request@master
        with:
          source_branch: feature/${{ env.version }}-cdn-update
          destination_branch: develop
          pr_title: "Updating CDN link to use @${{ env.version }}"
          pr_body: |
            Compiled JS files from last release are here:

              https://cdn.jsdelivr.net/gh/atk4/ui@${{ env.version }}/public/

          pr_reviewer: "romaninsh"
          pr_assignee: "romaninsh"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update to stable dependencies
        run: |
          # replaces X keys with X-release keys
          jq '. as $in | reduce (keys_unsorted[] | select(endswith("-release")|not)) as $k ({}; . + {($k) : (($k + "-release") as $kr | $in | if has($kr) then .[$kr] else .[$k] end) } )' < composer.json > tmp && mv tmp composer.json
          composer config version --unset

      - name: Compile JS files for CDN
        shell: bash
        run: |

          # Update version for the release branch
          v=$(echo ${{ github.ref }} | cut -d / -f 4)
          sed -i "s|public \$version.*|public \$version = '$v.0';|" src/App.php
          npm install -g less-plugin-clean-css
          (cd js; npm ci; npm run build; cd ..)
          lessc public/agileui.less public/agileui.css --clean-css="--s1 --advanced" --source-map
          echo '!agileui.css.map' >> public/.gitignore
          git add public
          git config --global user.email "bundler@agiletoolkit.org"
          git config --global user.name "Release Bundler"
          git commit -am "Releasing $v.0"
          echo "If everything is good and CI/CD pass - please manually create tag $v.0 on this commit ^^"

      - uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
